const constants = {
    FETCH_MOVIE_DATA: "FETCH_MOVIE_DATA",
    FETCH_MOVIE_DATA_SUCCESS: "FETCH_MOVIE_DATA_SUCCESS",
    FETCH_MOVIE_DATA_FAILURE: "FETCH_MOVIE_DATA_FAILURE",

    FETCH_CAST: "FETCH_CAST",
    FETCH_CAST_SUCCESS: "FETCH_CAST_SUCCESS",
    FETCH_CAST_FAILURE: "FETCH_CAST_FAILURE",
  
    CANCEL_FETCHING: "CANCEL_FETCHING",
  };
  
  
  export default constants;
  